In [1]:
import pandas as pd
import numpy as np

In [2]:
distances = pd.read_csv('data/distances.csv', sep=',',header=None)
distances.shape

(20, 20)

In [3]:
distances

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  \
0    0   4   9   6   5  49  51  54  53  53  53  55  53  56  54  53  53  55   
1    4   0   7   4   1  47  49  52  51  51  51  53  51  54  52  51  51  53   
2    9   7   0   4   6  48  50  53  52  52  52  54  52  55  53  52  52  54   
3    6   4   4   0   2  47  49  52  51  51  51  53  51  54  52  51  51  53   
4    5   1   6   2   0  48  50  53  52  52  52  54  52  55  53  52  52  54   
5   49  47  48  47  48   0  13  13   4   4  72  74  72  75  73  64  64  66   
6   51  49  50  49  50  13   0   1  13  13  74  76  74  77  75  66  66  68   
7   54  52  53  52  53  13   1   0  13  13  77  79  77  80  78  69  69  71   
8   53  51  52  51  52   4  13  13   0   1  76  78  76  79  77  68  68  70   
9   53  51  52  51  52   4  13  13   1   0  76  78  76  79  77  68  68  70   
10  53  51  52  51  52  72  74  77  76  76   0   8   7   9   2  52  52  54   
11  55  53  54  53  54  74  76  79  78  78   8   0   6   2   7  54  54  56   
12  53  51  52  51  52  72  74  77  76  76   7   6   0   7   6  52  52  54   
13  56  54  55  54  55  75  77  80  79  79   9   2   7   0   9  55  55  57   
14  54  52  53  52  53  73  75  78  77  77   2   7   6   9   0  53  53  55   
15  53  51  52  51  52  64  66  69  68  68  52  54  52  55  53   0   1  11   
16  53  51  52  51  52  64  66  69  68  68  52  54  52  55  53   1   0  10   
17  55  53  54  53  54  66  68  71  70  70  54  56  54  57  55  11  10   0   
18  55  53  54  53  54  66  68  71  70  70  54  56  54  57  55   8   8   8   
19  54  52  53  52  53  65  67  70  69  69  53  55  53  56  54   9   9   5   

    18  19  
0   55  54  
1   53  52  
2   54  53  
3   53  52  
4   54  53  
5   66  65  
6   68  67  
7   71  70  
8   70  69  
9   70  69  
10  54  53  
11  56  55  
12  54  53  
13  57  56  
14  55  54  
15   8   9  
16   8   9  
17   8   5  
18   0   7  
19   7   0

In [4]:
data = pd.read_csv('data/data.csv', sep=',', index_col=0)
data

Name  Must go?  \
Ride Number                                                                
0                                              Splash Mountain         0   
1                                              Haunted Mansion         0   
2                                               Space Mountain         0   
3                                      Seven Dwarfs Mine Train         1   
4                                            Its A Small World         0   
5                                              Spaceship Earth         0   
6                                               Mission: SPACE         0   
7                                                   Test Track         0   
8                                         Living With The Land         0   
9                                                      Soarin'         1   
10                               Twilight Zone Tower Of Terror         1   
11                                             Toy Story Mania         0   
12                                                  Star tours         0   
13                                             Slinky Dog Dash         0   
14                             Rock n roller coaster Aerosmith         0   
15                                          Navi River Journey         0   
16                                    Avatar Flight of Passage         1   
17           Expedition Everest: Legend Of The Forbidden Mo...         0   
18                                         Kilimanjaro Safaris         0   
19                                                 Kali River          0   

             Park Number  Happiness  Ride time (min)  Wait time OPT(mins)  \
Ride Number                                                                 
0                      1        9.0               11                   85   
1                      1        9.5                8                   50   
2                      1        8.5                3                   60   
3                      1       10.0                3                  110   
4                      1        6.0               11                   30   
5                      2        6.5               15                   20   
6                      2        5.0                6                   45   
7                      2        6.5                4                   80   
8                      2        4.0               14                   15   
9                      2       10.0                5                   40   
10                     3       10.0                5                   85   
11                     3        9.0                8                   50   
12                     3        7.5                5                   20   
13                     3        7.5                2                  100   
14                     3        7.5               17                  100   
15                     4        6.0                5                   75   
16                     4       10.0                5                  120   
17                     4       10.0                3                   45   
18                     4        7.0               19                   60   
19                     4        5.5                4                   45   

             Wait time PES(mins)  
Ride Number                       
0                            180  
1                             55  
2                            175  
3                            150  
4                             45  
5                             35  
6                             50  
7                             85  
8                             25  
9                             70  
10                            95  
11                            75  
12                            35  
13                           105  
14                           105  
15                            85  
16                           200  
17                       

In [27]:
distance_matrix = distances.values
happiness = data['Happiness'].values
ride_time = data['Ride time (min)'].values
opt_wait_time = data['Wait time OPT(mins)'].values
pes_wait_time = data['Wait time PES(mins)'].values
names = data['Name'].values

In [17]:
from core.tsp_solver import tsp_solver

In [18]:
tour = tsp_solver(distance_matrix)

225
222
Starting annealing.
Best fitness obtained:  222
Improvement over greedy heuristic:  5.13%


In [19]:
tour

[13, 11, 12, 14, 10, 15, 16, 18, 19, 17, 0, 1, 4, 3, 2, 5, 8, 9, 6, 7]

In [20]:
def get_tour_happiness(tour, happiness):
    return np.sum(happiness[tour])

In [21]:
get_tour_happiness(tour, happiness)

155.0

In [23]:
from core.approx_tsp import route_distance
def get_tour_time(tour, distance_matrix):
    return route_distance(tour, distance_matrix)

In [24]:
get_tour_time(tour, distance_matrix)

222

In [26]:
np.sum(ride_time[tour])

153

In [29]:
names[[0,4,5]]

array(['Splash Mountain', 'Its A Small World', 'Spaceship Earth'],
      dtype=object)

In [33]:
visited_indices = np.array([1,3,4])

In [31]:
distance_matrix[visited_indices, :][:, visited_indices]

array([[0, 4, 1],
       [4, 0, 2],
       [1, 2, 0]])

In [32]:
foo = [2,0,1]

In [34]:
visited_indices[foo]

array([4, 1, 3])

In [35]:
np.array(visited_indices)

array([1, 3, 4])

In [36]:
must_go = data['Must go?'].values

In [43]:
set(np.where(must_go)[0])

{3, 9, 10, 16}

In [44]:
set(np.where(data['Must go?'].values)[0])

{3, 9, 10, 16}